// SPDX-License-Identifier: Apache-2.0
// Package resolver implements the Semantic Attach Resolver. It recovers the
// plaintext TLS boundary file-offsets for an agent process so the Semantic
// Sensor can attach uprobes by offset (func_name=NULL) rather than by symbol
// name: uprobes need only a file offset, and stripping removes names, not code.
package resolver

import (
	"debug/elf"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"hash/fnv"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
	"time"

	"go.uber.org/zap"
	"golang.org/x/sync/singleflight"

	"github.com/boanlab/agentknox/pkg/types"
)

// logical offset keys used across the AttachPlan.Offsets map.
const (
	keyRead         = "read"
	keyWrite        = "write"
	keyHandshake    = "handshake"
	keyAEADOpen     = "aead_open"
	keyAEADSeal     = "aead_seal"
	keyChachaOpen   = "chacha_open"
	keyChachaSeal   = "chacha_seal"
	keyAESGCMDec    = "aesni_gcm_dec"
	keyAESGCMEnc    = "aesni_gcm_enc"
	keyAESGCMDec512 = "aes_gcm_dec_avx512"
	keyAESGCMEnc512 = "aes_gcm_enc_avx512"
)

// asmSymbols maps a logical offset key to the CRYPTOGAMS assembly AEAD function:
// the plaintext boundary for a stripped rustls/aws-lc-rs binary (Codex), where the
// C EVP_AEAD_CTX_* wrappers vary too much between builds to signature. The
// assembly is toolchain-independent (generated by perlasm) but changes across
// aws-lc-sys versions (its aws_lc_X_Y_Z symbol prefix), so extraction matches by
// suffix.
//
// Hosts dispatch AES-GCM by CPU (aesni_gcm_* vs aes_gcm_*_avx512); ChaCha20 uses
// chacha20_poly1305_*. All are hooked since a session negotiates only one.
var asmSymbols = map[string]string{
	keyChachaOpen:   "chacha20_poly1305_open",
	keyChachaSeal:   "chacha20_poly1305_seal",
	keyAESGCMDec:    "aesni_gcm_decrypt",
	keyAESGCMEnc:    "aesni_gcm_encrypt",
	keyAESGCMDec512: "aes_gcm_decrypt_avx512",
	keyAESGCMEnc512: "aes_gcm_encrypt_avx512",
}

const providerAEADAsm = "aws-lc-asm"

// sslSymbols maps a logical offset key to the exported symbol name that carries
// the OpenSSL/BoringSSL plaintext boundary.
var sslSymbols = map[string]string{
	keyRead:      "SSL_read",
	keyWrite:     "SSL_write",
	keyHandshake: "SSL_do_handshake",
}

// versionRe extracts an embedded provider/version banner from a TLS library so
// that a build can be classified when a build-id alone is insufficient.
var versionRe = regexp.MustCompile(`(OpenSSL\s+[0-9][^\x00\n]{0,32}|BoringSSL[^\x00\n]{0,32}|aws-lc[^\x00\n]{0,32})`)

// Resolver recovers plaintext boundary offsets. It implements pipeline.Resolver.
//
// Resolved plans are cached by a content fingerprint of the target binary: the
// first process of a build pays the .text scan, and every later process of the
// same build (a re-exec worker, a concurrent agent, a repeat invocation) attaches
// instantly from cache, which is what lets uprobes win the attach race for
// short-lived and re-execing agents. Concurrent resolutions of the same new
// build coalesce via singleflight.
type Resolver struct {
	offsetDBPath string
	signatures   []signature // T5 prologue signatures (from signatures.json)
	log          *zap.Logger

	mu    sync.RWMutex
	cache map[string]*types.AttachPlan // fingerprint -> resolved plan (build-specific offsets)
	// textSeen maps a binary's code-section fingerprint to the build-id it was
	// first resolved under. A later binary with the same code under a different
	// build-id has had its identity changed without its code changing, which is the
	// tamper signal a reference set alone cannot give.
	textSeen map[string]string
	sf       singleflight.Group
}

// New constructs a Resolver. offsetDBPath points at the JSON build-id→offset
// cache (T4); a "signatures.json" sibling supplies T5 prologue signatures. Both
// are optional — a missing file is tolerated (other tiers still apply).
func New(offsetDBPath string, log *zap.Logger) *Resolver {
	if log == nil {
		log = zap.NewNop()
	}
	r := &Resolver{offsetDBPath: offsetDBPath, log: log,
		cache: make(map[string]*types.AttachPlan), textSeen: make(map[string]string)}
	if offsetDBPath != "" {
		sigPath := filepath.Join(filepath.Dir(offsetDBPath), "signatures.json")
		if sigs, err := loadSignatures(sigPath); err != nil {
			log.Warn("resolver: load signatures failed", zap.String("path", sigPath), zap.Error(err))
		} else if len(sigs) > 0 {
			r.signatures = sigs
			log.Info("resolver: loaded T5 signatures", zap.Int("count", len(sigs)))
		}
	}
	return r
}

// Resolve runs the offset-recovery ladder for pid and returns an AttachPlan.
// Degraded or absent coverage is a valid (non-error) outcome: the caller can
// still enforce at the system layer. An error is returned only when the target
// process/binary cannot be inspected at all.
func (r *Resolver) Resolve(pid int32, agent types.AgentKind) (*types.AttachPlan, error) {
	target, err := r.selectTarget(pid)
	if err != nil {
		return nil, fmt.Errorf("resolve pid %d: %w", pid, err)
	}

	key := r.fingerprint(target.binaryPath)
	if key != "" {
		r.mu.RLock()
		cached, ok := r.cache[key]
		r.mu.RUnlock()
		if ok {
			return retargetPlan(cached, target), nil
		}
		// Coalesce concurrent scans of the same new build into one.
		v, err, _ := r.sf.Do(key, func() (any, error) {
			p, err := r.resolveScan(pid, agent, target)
			if err == nil && p != nil && p.Coverage != types.CoverageNone && len(p.Offsets) > 0 {
				r.mu.Lock()
				r.cache[key] = p
				r.mu.Unlock()
			}
			return p, err
		})
		if err != nil {
			return nil, err
		}
		return retargetPlan(v.(*types.AttachPlan), target), nil
	}
	return r.resolveScan(pid, agent, target)
}

// fingerprint returns a cheap content key for a binary: its build-id when
// present, else a hash of the .text size plus a few sampled 4 KiB windows (stable
// across byte-identical re-exec copies, distinct across builds). Empty on error.
func (r *Resolver) fingerprint(path string) string {
	f, err := elf.Open(path)
	if err != nil {
		return ""
	}
	defer f.Close()
	if bid := readBuildID(f); bid != "" {
		return "bid:" + bid
	}
	return textFingerprint(f)
}

// textFingerprint hashes the binary's code section: its size plus a few sampled
// 4 KiB windows. Stable across byte-identical copies, distinct across builds, and
// independent of the build-id, which is what lets a changed identity over
// unchanged code be recognized. Empty when there is no code section to hash.
func textFingerprint(f *elf.File) string {
	text := f.Section(".text")
	if text == nil || text.Size == 0 {
		return ""
	}
	h := fnv.New64a()
	var szb [8]byte
	binary.LittleEndian.PutUint64(szb[:], text.Size)
	_, _ = h.Write(szb[:])
	sr := text.Open()
	buf := make([]byte, 4096)
	offsets := []int64{0, int64(text.Size) / 2, int64(text.Size) - 4096}
	for _, off := range offsets {
		if off < 0 {
			off = 0
		}
		if _, err := sr.Seek(off, io.SeekStart); err != nil {
			continue
		}
		n, _ := io.ReadFull(sr, buf)
		_, _ = h.Write(buf[:n])
	}
	return fmt.Sprintf("fp:%x", h.Sum64())
}

// noteIdentity records which build-id this code section was first seen under and
// reports the previous one. Only identified binaries participate: a build with no
// build-id says nothing about the identity of one that has it.
func (r *Resolver) noteIdentity(textFP, buildID string) (prev string, seen bool) {
	if textFP == "" || buildID == "" {
		return "", false
	}
	r.mu.Lock()
	defer r.mu.Unlock()
	prev, seen = r.textSeen[textFP]
	if !seen {
		r.textSeen[textFP] = buildID
	}
	return prev, seen
}

// knownGoodSet returns the build-ids the offset database vouches for. It is the
// supply-chain reference the resolver compares an agent binary against, and it is
// consulted for every build, not only for one that descends as far as the T4 rung:
// an unstripped binary resolves at T1 and must still be checked.
func (r *Resolver) knownGoodSet() map[string]map[string]uint64 {
	db, err := LoadOffsetDB(r.offsetDBPath)
	if err != nil {
		r.log.Warn("offsetdb load failed", zap.String("path", r.offsetDBPath), zap.Error(err))
		return nil
	}
	return db
}

// retargetPlan returns a copy of a cached plan bound to a specific process's
// binary path (the offsets are content-identical across re-exec copies, but each
// process maps its own on-disk path, which Attach opens). The Offsets map is
// deep-copied so the shared cache entry is never mutated.
func retargetPlan(cached *types.AttachPlan, target targetBinary) *types.AttachPlan {
	p := *cached
	p.BinaryPath = target.binaryPath
	p.Library = target.library
	if cached.Offsets != nil {
		p.Offsets = make(map[string]uint64, len(cached.Offsets))
		for k, v := range cached.Offsets {
			p.Offsets[k] = v
		}
	}
	return &p
}

// resolveScan performs the full offset-recovery ladder (the expensive path).
func (r *Resolver) resolveScan(pid int32, agent types.AgentKind, target targetBinary) (*types.AttachPlan, error) {
	f, err := elf.Open(target.binaryPath)
	if err != nil {
		return nil, fmt.Errorf("open elf %s: %w", target.binaryPath, err)
	}
	defer f.Close()

	buildID := readBuildID(f)
	version := readVersion(f)

	plan := &types.AttachPlan{
		BinaryPath: target.binaryPath,
		Library:    target.library,
		BuildID:    buildID,
		Boundary:   types.BoundaryNone,
		Tier:       types.TierFailed,
		Coverage:   types.CoverageNone,
		Offsets:    map[string]uint64{},
	}
	// Binary identity, decided before the ladder descends. Two independent
	// questions: does a known-good reference set vouch for this build-id, and has
	// this code section been seen before under a different one.
	known := r.knownGoodSet()
	if len(known) > 0 {
		plan.ReferenceSet = true
		if buildID != "" {
			_, plan.KnownGood = known[buildID]
		}
	}
	if prev, seen := r.noteIdentity(textFingerprint(f), buildID); seen && prev != buildID {
		plan.IdentityChanged = true
		r.log.Warn("resolver: code section matches a build already resolved under a different build-id",
			zap.String("binary", target.binaryPath),
			zap.String("build_id", buildID), zap.String("previous_build_id", prev))
	}

	r.log.Debug("resolver fingerprint",
		zap.Int32("pid", pid),
		zap.String("agent", string(agent)),
		zap.String("binary", target.binaryPath),
		zap.String("library", target.library),
		zap.String("build_id", buildID),
		zap.String("version", version))

	// Go crypto/tls: pure-Go TLS clients (e.g. Crush) have no SSL_* symbols; their
	// boundary is crypto/tls.(*Conn).Read/Write, resolved by symbol.
	if offs, readRets, ok := resolveGoTLS(f); ok {
		r.applyGoTLS(plan, offs, readRets)
		return plan, nil
	}

	// T1 (.dynsym) → T2 (.symtab): recover SSL_read/SSL_write/SSL_do_handshake
	// export offsets directly from the binary's own symbol tables.
	if offs := symbolOffsets(f, f.DynamicSymbols); len(offs) > 0 {
		r.applySSL(plan, offs, types.TierDynsym, 0.95)
		return plan, nil
	}
	if offs := symbolOffsets(f, f.Symbols); len(offs) > 0 {
		r.applySSL(plan, offs, types.TierSymtab, 0.9)
		return plan, nil
	}

	// T3: build-id → debuginfod/separated DWARF.
	if offs, ok := resolveDebuginfod(f, buildID); ok {
		r.applySSL(plan, offs, types.TierDebuginfod, 0.85)
		return plan, nil
	}

	// T4: build-id → offset cache DB (the same set consulted for known-good above).
	if buildID != "" {
		if entry, ok := known[buildID]; ok {
			r.applyDB(plan, entry)
			return plan, nil
		}
	}

	// T5: prologue pattern match against an open-source reference build.
	if offs, ok := resolvePatternMatchWith(f, r.signatures, providerFor(plan.Library, version)); ok {
		r.applySSL(plan, offs, types.TierPatternMatch, 0.7)
		return plan, nil
	}
	// T5, AEAD assembly: the same matcher against the CRYPTOGAMS kernels, which
	// ExtractSignatures fingerprints under their own provider. This is the only
	// rung that reaches a fully stripped static binary, since it needs neither a
	// build-id nor a surviving symbol; providerFor never names this provider, so
	// it is tried explicitly rather than derived from the library string.
	if offs, ok := resolvePatternMatchWith(f, r.signatures, providerAEADAsm); ok {
		r.applyASM(plan, offs)
		return plan, nil
	}
	// T6: recover an unnamed boundary by cross-reference from a resolved anchor.
	// No partial anchors reach this rung, since every earlier rung returns on
	// success (see xref.go).
	if offs, ok := resolveXref(f, plan.Offsets); ok {
		r.applySSL(plan, offs, types.TierXref, 0.6)
		return plan, nil
	}
	// T7: move the boundary to the AEAD layer (rustls/aws-lc-rs).
	if offs, ok := resolveAEADBoundary(f); ok {
		for k, v := range offs {
			plan.Offsets[k] = v
		}
		plan.Boundary = types.BoundaryAEAD
		plan.Tier = types.TierBoundaryMove
		plan.Confidence = 0.6
		plan.Coverage = coverageFor(offs)
		return plan, nil
	}
	// A stripped rustls/aws-lc-rs agent (Codex) may have no attachable, portable
	// TLS plaintext boundary: its C AEAD wrappers carry no symbol, and the
	// CRYPTOGAMS assembly path is CPU-microarchitecture-dependent (VAES/AVX512 vs
	// aesni use different register ABIs). Rather than attach a boundary it cannot
	// deliver, such a binary falls through to a valid coverage "none" plan; its
	// content comes from the agent's session transcript and enforcement from the
	// system layer.

	// None matched: return a valid degraded/none plan (do NOT error).
	r.log.Info("resolver: no offsets recovered, degraded coverage",
		zap.Int32("pid", pid), zap.String("build_id", buildID))
	return plan, nil
}

// ExtractOffsets recovers boundary offsets from a binary's own symbol tables —
// the automatic path for the offset-DB generator. It returns the build-id and
// the SSL (T1/T2) and AEAD (T7) offsets found by symbol name. A stripped binary
// yields an empty map (its offsets must come from a reference build or manual RE).
func ExtractOffsets(path string) (buildID string, offsets map[string]uint64, err error) {
	f, err := elf.Open(path)
	if err != nil {
		return "", nil, err
	}
	defer f.Close()
	buildID = readBuildID(f)
	offsets = map[string]uint64{}
	if o := symbolOffsets(f, f.DynamicSymbols); len(o) > 0 {
		for k, v := range o {
			offsets[k] = v
		}
	}
	for k, v := range symbolOffsets(f, f.Symbols) {
		if _, ok := offsets[k]; !ok {
			offsets[k] = v
		}
	}
	if o, ok := resolveAEADBoundary(f); ok {
		for k, v := range o {
			offsets[k] = v
		}
	}
	return buildID, offsets, nil
}

// FindProcessTLSLib returns the path of the TLS library a running process has
// loaded (libssl preferred), for the generator's --pid mode.
func FindProcessTLSLib(pid int32) (string, bool) { return findTLSLibrary(pid) }

// targetBinary is the resolved file the uprobes will attach to.
type targetBinary struct {
	binaryPath string // absolute path to attach to (.so if dynamic, else exe)
	library    string // logical library label (e.g. libssl.so.3 | <self>)
}

// selectTarget picks the binary carrying the TLS boundary: a dynamically loaded
// libssl/libcrypto/BoringSSL object if present in the process map, otherwise the
// executable itself (static link / embedded BoringSSL as in stripped Bun).
func (r *Resolver) selectTarget(pid int32) (targetBinary, error) {
	exe, err := os.Readlink(fmt.Sprintf("/proc/%d/exe", pid))
	if err != nil {
		return targetBinary{}, fmt.Errorf("read exe link: %w", err)
	}
	if lib, ok := findTLSLibrary(pid); ok {
		return targetBinary{binaryPath: lib, library: baseName(lib)}, nil
	}
	return targetBinary{binaryPath: exe, library: "<self>"}, nil
}

// findTLSLibrary scans /proc/<pid>/maps for a loaded TLS library carrying the
// plaintext boundary and returns its on-disk path. libssl is preferred because
// the SSL_read/SSL_write boundary lives there; a static BoringSSL object carries
// both APIs; libcrypto is only a fallback (it carries the EVP_AEAD boundary but
// not SSL_read/write, so it must never be preferred over libssl).
func findTLSLibrary(pid int32) (string, bool) {
	data, err := os.ReadFile(fmt.Sprintf("/proc/%d/maps", pid))
	if err != nil {
		return "", false
	}
	var paths []string
	for _, line := range strings.Split(string(data), "\n") {
		fields := strings.Fields(line)
		if len(fields) < 6 {
			continue
		}
		if p := fields[5]; strings.HasPrefix(p, "/") {
			paths = append(paths, p)
		}
	}
	if lib := pickTLSLib(paths); lib != "" {
		return lib, true
	}
	return "", false
}

func baseName(path string) string {
	if i := strings.LastIndexByte(path, '/'); i >= 0 {
		return path[i+1:]
	}
	return path
}

// symbolOffsets locates the SSL boundary symbols using the supplied symbol
// accessor (DynamicSymbols for T1, Symbols for T2) and converts each symbol's
// virtual address to a file offset. Returns keyed file offsets.
func symbolOffsets(f *elf.File, symsFn func() ([]elf.Symbol, error)) map[string]uint64 {
	return symbolOffsetsWith(f, symsFn, sslSymbols)
}

// aeadSymbolOffsets recovers EVP_AEAD_CTX_open/seal offsets from both symbol
// tables (aws-lc-rs/rustls, when the reference build exports them by name).
func aeadSymbolOffsets(f *elf.File) map[string]uint64 {
	offs := symbolOffsetsWith(f, f.DynamicSymbols, aeadSymbols)
	for k, v := range symbolOffsetsWith(f, f.Symbols, aeadSymbols) {
		if _, ok := offs[k]; !ok {
			offs[k] = v
		}
	}
	return offs
}

// symbolOffsetsBySuffix resolves file offsets by matching each symbol whose name
// ENDS WITH a mapped base name. Used for the AEAD assembly, whose reference-build
// symbols carry an aws-lc-sys version prefix (aws_lc_0_39_1_chacha20_poly1305_open).
func symbolOffsetsBySuffix(f *elf.File, symsFn func() ([]elf.Symbol, error), symMap map[string]string) map[string]uint64 {
	syms, err := symsFn()
	if err != nil || len(syms) == 0 {
		return nil
	}
	out := map[string]uint64{}
	for _, s := range syms {
		if s.Value == 0 {
			continue
		}
		for key, base := range symMap {
			if s.Name == base || strings.HasSuffix(s.Name, "_"+base) {
				if off, ok := vaddrToFileOffset(f, s.Value); ok {
					out[key] = off
				}
			}
		}
	}
	return out
}

// symbolOffsetsWith resolves the file offsets of a given logical-key→symbol-name
// map (sslSymbols or aeadSymbols) from one symbol table.
func symbolOffsetsWith(f *elf.File, symsFn func() ([]elf.Symbol, error), symMap map[string]string) map[string]uint64 {
	syms, err := symsFn()
	if err != nil || len(syms) == 0 {
		return nil
	}
	want := map[string]string{} // symbol name → logical key
	for key, name := range symMap {
		want[name] = key
	}
	out := map[string]uint64{}
	for _, s := range syms {
		key, ok := want[s.Name]
		if !ok || s.Value == 0 {
			continue
		}
		if off, ok := vaddrToFileOffset(f, s.Value); ok {
			out[key] = off
		}
	}
	return out
}

// vaddrToFileOffset converts a symbol virtual address to a file offset using the
// containing PT_LOAD program header: fileoff = vaddr - p.Vaddr + p.Off.
func vaddrToFileOffset(f *elf.File, vaddr uint64) (uint64, bool) {
	for _, p := range f.Progs {
		if p.Type != elf.PT_LOAD {
			continue
		}
		if vaddr >= p.Vaddr && vaddr < p.Vaddr+p.Filesz {
			return vaddr - p.Vaddr + p.Off, true
		}
	}
	return 0, false
}

// applySSL fills the plan from recovered SSL offsets and sets coverage based on
// whether both read and write boundaries were found.
func (r *Resolver) applySSL(plan *types.AttachPlan, offs map[string]uint64, tier types.AttachTier, confidence float64) {
	for k, v := range offs {
		plan.Offsets[k] = v
	}
	plan.Boundary = types.BoundarySSL
	plan.Tier = tier
	plan.Confidence = confidence
	plan.Coverage = coverageFor(offs)
}

// applyDB fills the plan from a T4 offset-DB entry. A matching build-id entry is
// treated as known-good (supply-chain reference). Both SSL and AEAD keys are
// honored so the same DB can serve rustls/aws-lc-rs boundaries.
func (r *Resolver) applyDB(plan *types.AttachPlan, entry map[string]uint64) {
	for _, k := range []string{keyRead, keyWrite, keyHandshake, keyAEADOpen, keyAEADSeal} {
		if v, ok := entry[k]; ok {
			plan.Offsets[k] = v
		}
	}
	plan.Tier = types.TierOffsetDB
	plan.KnownGood = true
	plan.Confidence = 0.99
	if _, hasAEAD := entry[keyAEADOpen]; hasAEAD {
		plan.Boundary = types.BoundaryAEAD
		plan.Coverage = coverageForAEAD(plan.Offsets)
	} else {
		plan.Boundary = types.BoundarySSL
		plan.Coverage = coverageFor(plan.Offsets)
	}
}

// coverageFor reports coverage for an SSL boundary: full when both read and
// write are present, degraded when exactly one is, none when neither.
func coverageFor(offs map[string]uint64) types.SemanticCoverage {
	_, hasRead := offs[keyRead]
	_, hasWrite := offs[keyWrite]
	switch {
	case hasRead && hasWrite:
		return types.CoverageFull
	case hasRead || hasWrite:
		return types.CoverageDegraded
	default:
		return types.CoverageNone
	}
}

// applyASM fills the plan from recovered CRYPTOGAMS AEAD assembly offsets (the
// stripped rustls/aws-lc-rs boundary, e.g. Codex).
func (r *Resolver) applyASM(plan *types.AttachPlan, offs map[string]uint64) {
	for k, v := range offs {
		plan.Offsets[k] = v
	}
	plan.Boundary = types.BoundaryAEADAsm
	plan.Tier = types.TierPatternMatch
	plan.Confidence = 0.7
	plan.Coverage = coverageForAsm(offs)
}

// coverageForAsm reports coverage for the AEAD-assembly boundary: an inbound
// (decrypt) and an outbound (encrypt/seal) path in either cipher family suffices
// for full — a session negotiates one AEAD, so one family present is enough.
func coverageForAsm(offs map[string]uint64) types.SemanticCoverage {
	_, chaOpen := offs[keyChachaOpen]
	_, chaSeal := offs[keyChachaSeal]
	_, gcmDec := offs[keyAESGCMDec]
	_, gcmEnc := offs[keyAESGCMEnc]
	_, gcmDec512 := offs[keyAESGCMDec512]
	_, gcmEnc512 := offs[keyAESGCMEnc512]
	inbound := chaOpen || gcmDec || gcmDec512
	outbound := chaSeal || gcmEnc || gcmEnc512
	switch {
	case inbound && outbound:
		return types.CoverageFull
	case inbound || outbound:
		return types.CoverageDegraded
	default:
		return types.CoverageNone
	}
}

// coverageForAEAD reports coverage for an AEAD boundary (rustls/aws-lc-rs).
func coverageForAEAD(offs map[string]uint64) types.SemanticCoverage {
	_, hasOpen := offs[keyAEADOpen]
	_, hasSeal := offs[keyAEADSeal]
	switch {
	case hasOpen && hasSeal:
		return types.CoverageFull
	case hasOpen || hasSeal:
		return types.CoverageDegraded
	default:
		return types.CoverageNone
	}
}

// readBuildID extracts the GNU build-id from .note.gnu.build-id as a lowercase
// hex string, or "" if absent/malformed.
func readBuildID(f *elf.File) string {
	sec := f.Section(".note.gnu.build-id")
	if sec == nil {
		return ""
	}
	data, err := sec.Data()
	if err != nil {
		return ""
	}
	// ELF note: namesz(4) descsz(4) type(4) name[namesz→4-aligned] desc[descsz].
	if len(data) < 12 {
		return ""
	}
	order := f.ByteOrder
	nameSz := order.Uint32(data[0:4])
	descSz := order.Uint32(data[4:8])
	// Skip fixed header + 4-aligned name.
	off := 12 + align4(nameSz)
	end := off + descSz
	if descSz == 0 || uint64(end) > uint64(len(data)) {
		return ""
	}
	return hex.EncodeToString(data[off:end])
}

func align4(n uint32) uint32 { return (n + 3) &^ 3 }

// readVersion scans the read-only data for an embedded provider/version banner.
// It prefers a banner carrying a version number and skips format strings (e.g.
// "BoringSSL error occurred: %s"), which otherwise get mistaken for a version.
func readVersion(f *elf.File) string {
	var fallback string
	for _, name := range []string{".rodata", ".data.rel.ro"} {
		sec := f.Section(name)
		if sec == nil {
			continue
		}
		data, err := sec.Data()
		if err != nil {
			continue
		}
		for _, m := range versionRe.FindAll(data, -1) {
			s := strings.TrimSpace(string(m))
			if strings.Contains(s, "%") {
				continue // format string, not a version banner
			}
			if strings.ContainsAny(s, "0123456789") {
				return s // a banner with a version number: best match
			}
			if fallback == "" {
				fallback = s
			}
		}
	}
	return fallback
}

// LoadOffsetDB reads the build-id→offset JSON cache. A missing file is not an
// error: it returns an empty map so callers can proceed with other tiers.
// Format: {"<buildid>": {"read":123,"write":456,"handshake":789,
// "aead_open":...,"aead_seal":...}}.
func LoadOffsetDB(path string) (map[string]map[string]uint64, error) {
	if path == "" {
		return map[string]map[string]uint64{}, nil
	}
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return map[string]map[string]uint64{}, nil
		}
		return nil, fmt.Errorf("read offsetdb %s: %w", path, err)
	}
	var db map[string]map[string]uint64
	if err := json.Unmarshal(data, &db); err != nil {
		return nil, fmt.Errorf("parse offsetdb %s: %w", path, err)
	}
	if db == nil {
		db = map[string]map[string]uint64{}
	}
	return db, nil
}

// ---------------------------------------------------------------------------
// Ladder rungs T3, T5, T6, T7.
// ---------------------------------------------------------------------------

// resolveDebuginfod (T3) fetches separated symbols/DWARF for the binary's
// build-id from a debuginfod server, resolves the SSL boundary symbols in the
// fetched debug object, and converts their virtual addresses to file offsets in
// the ORIGINAL binary (same build-id ⇒ same load layout). Network is used only
// when DEBUGINFOD_URLS is set, so the resolver stays offline-safe by default.
func resolveDebuginfod(orig *elf.File, buildID string) (map[string]uint64, bool) {
	if buildID == "" {
		return nil, false
	}
	urls := os.Getenv("DEBUGINFOD_URLS")
	if urls == "" {
		return nil, false // no server configured: skip (offline default)
	}
	for _, base := range strings.Fields(urls) {
		debugPath, ok := fetchDebuginfod(base, buildID)
		if !ok {
			continue
		}
		df, err := elf.Open(debugPath)
		if err != nil {
			continue
		}
		vaddrs := symbolVaddrs(df)
		_ = df.Close()
		if len(vaddrs) == 0 {
			continue
		}
		out := map[string]uint64{}
		for k, va := range vaddrs {
			if off, ok := vaddrToFileOffset(orig, va); ok {
				out[k] = off
			}
		}
		if len(out) > 0 {
			return out, true
		}
	}
	return nil, false
}

// fetchDebuginfod downloads the debuginfo object for buildID from a debuginfod
// server into a local cache and returns the cached path.
func fetchDebuginfod(base, buildID string) (string, bool) {
	cacheDir := filepath.Join(os.TempDir(), "agentknox-debuginfod")
	if err := os.MkdirAll(cacheDir, 0o750); err != nil {
		return "", false
	}
	dst := filepath.Join(cacheDir, buildID+".debug")
	if fi, err := os.Stat(dst); err == nil && fi.Size() > 0 {
		return dst, true // cached
	}
	url := strings.TrimRight(base, "/") + "/buildid/" + buildID + "/debuginfo"
	client := &http.Client{Timeout: 15 * time.Second}
	// URL base is DEBUGINFOD_URLS (operator-configured, trusted); path is a hex
	// build-id. This is the intended debuginfod protocol fetch.
	resp, err := client.Get(url) // #nosec G704 -- operator-configured debuginfod server
	if err != nil {
		return "", false
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return "", false
	}
	tmp := dst + ".tmp"
	out, err := os.Create(tmp)
	if err != nil {
		return "", false
	}
	if _, err := io.Copy(out, resp.Body); err != nil {
		_ = out.Close()
		_ = os.Remove(tmp)
		return "", false
	}
	_ = out.Close()
	if err := os.Rename(tmp, dst); err != nil {
		return "", false
	}
	return dst, true
}

// symbolVaddrs returns the SSL boundary symbols' virtual addresses from a debug
// object's symbol tables (either table may carry them).
func symbolVaddrs(f *elf.File) map[string]uint64 {
	want := map[string]string{}
	for key, name := range sslSymbols {
		want[name] = key
	}
	out := map[string]uint64{}
	for _, symsFn := range []func() ([]elf.Symbol, error){f.Symbols, f.DynamicSymbols} {
		syms, err := symsFn()
		if err != nil {
			continue
		}
		for _, s := range syms {
			if key, ok := want[s.Name]; ok && s.Value != 0 {
				out[key] = s.Value
			}
		}
	}
	return out
}

// aeadSymbols maps a logical offset key to the aws-lc/aws-lc-rs AEAD boundary
// symbol. Rustls (Codex) has no stable SSL_read; the plaintext record is instead
// at EVP_AEAD_CTX_open (just-decrypted inbound) / EVP_AEAD_CTX_seal (about-to-
// encrypt outbound).
var aeadSymbols = map[string]string{
	keyAEADOpen: "EVP_AEAD_CTX_open",
	keyAEADSeal: "EVP_AEAD_CTX_seal",
}

// resolveAEADBoundary (T7) recovers the AEAD decrypt/encrypt boundary offsets for
// stacks without a stable SSL_read (rustls/aws-lc-rs, e.g. Codex) by looking up
// the AEAD symbols in both symbol tables. A fully stripped build falls through
// (names gone); a T4 offset-DB entry or T5 signature is then required.
func resolveAEADBoundary(f *elf.File) (map[string]uint64, bool) {
	want := map[string]string{}
	for key, name := range aeadSymbols {
		want[name] = key
	}
	out := map[string]uint64{}
	for _, symsFn := range []func() ([]elf.Symbol, error){f.DynamicSymbols, f.Symbols} {
		syms, err := symsFn()
		if err != nil {
			continue
		}
		for _, s := range syms {
			if key, ok := want[s.Name]; ok && s.Value != 0 {
				if off, ok := vaddrToFileOffset(f, s.Value); ok {
					out[key] = off
				}
			}
		}
	}
	if len(out) == 0 {
		return nil, false
	}
	return out, true
}
