// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 BoanLab @ Dankook University
//
// AgentKnox gRPC transport. The daemon streams and replays events over the
// AgentKnoxExport service; daemons forward to a central collector over the
// AgentKnoxAggregator service. Event payloads travel as JSON-encoded
// pkg/types.* values inside an Envelope, so the wire contract stays faithful to
// the canonical Go types without mirroring every nested field here.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: protobuf/agentknox.proto

package agentknoxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope wraps one event. data is the JSON encoding of the pkg/types value
// named by kind.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // syscall|semantic|action|alert|edge
	TimeUnixNano  int64                  `protobuf:"varint,2,opt,name=time_unix_nano,json=timeUnixNano,proto3" json:"time_unix_nano,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // JSON of *types.SyscallEvent / SemanticEvent / ...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_protobuf_agentknox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agentknox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_protobuf_agentknox_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Envelope) GetTimeUnixNano() int64 {
	if x != nil {
		return x.TimeUnixNano
	}
	return 0
}

func (x *Envelope) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kinds         []string               `protobuf:"bytes,1,rep,name=kinds,proto3" json:"kinds,omitempty"` // empty = all kinds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_protobuf_agentknox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agentknox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_agentknox_proto_rawDescGZIP(), []int{1}
}

func (x *StreamRequest) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

type RecentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`    // empty = alert
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 0 = server default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentRequest) Reset() {
	*x = RecentRequest{}
	mi := &file_protobuf_agentknox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentRequest) ProtoMessage() {}

func (x *RecentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agentknox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentRequest.ProtoReflect.Descriptor instead.
func (*RecentRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_agentknox_proto_rawDescGZIP(), []int{2}
}

func (x *RecentRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RecentRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Envelope            `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentResponse) Reset() {
	*x = RecentResponse{}
	mi := &file_protobuf_agentknox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentResponse) ProtoMessage() {}

func (x *RecentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agentknox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentResponse.ProtoReflect.Descriptor instead.
func (*RecentResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_agentknox_proto_rawDescGZIP(), []int{3}
}

func (x *RecentResponse) GetEvents() []*Envelope {
	if x != nil {
		return x.Events
	}
	return nil
}

type SessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionsRequest) Reset() {
	*x = SessionsRequest{}
	mi := &file_protobuf_agentknox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionsRequest) ProtoMessage() {}

func (x *SessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agentknox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionsRequest.ProtoReflect.Descriptor instead.
func (*SessionsRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_agentknox_proto_rawDescGZIP(), []int{4}
}

type SessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      [][]byte               `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionsResponse) Reset() {
	*x = SessionsResponse{}
	mi := &file_protobuf_agentknox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionsResponse) ProtoMessage() {}

func (x *SessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agentknox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionsResponse.ProtoReflect.Descriptor instead.
func (*SessionsResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_agentknox_proto_rawDescGZIP(), []int{5}
}

func (x *SessionsResponse) GetSessions() [][]byte {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type PoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoliciesRequest) Reset() {
	*x = PoliciesRequest{}
	mi := &file_protobuf_agentknox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoliciesRequest) ProtoMessage() {}

func (x *PoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agentknox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoliciesRequest.ProtoReflect.Descriptor instead.
func (*PoliciesRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_agentknox_proto_rawDescGZIP(), []int{6}
}

type PoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summaries     []byte                 `protobuf:"bytes,1,opt,name=summaries,proto3" json:"summaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoliciesResponse) Reset() {
	*x = PoliciesResponse{}
	mi := &file_protobuf_agentknox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoliciesResponse) ProtoMessage() {}

func (x *PoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agentknox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoliciesResponse.ProtoReflect.Descriptor instead.
func (*PoliciesResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_agentknox_proto_rawDescGZIP(), []int{7}
}

func (x *PoliciesResponse) GetSummaries() []byte {
	if x != nil {
		return x.Summaries
	}
	return nil
}

type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"` // node name of the sending daemon
	Events        []*Envelope            `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_protobuf_agentknox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agentknox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_agentknox_proto_rawDescGZIP(), []int{8}
}

func (x *IngestRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IngestRequest) GetEvents() []*Envelope {
	if x != nil {
		return x.Events
	}
	return nil
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      uint32                 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_protobuf_agentknox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agentknox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_agentknox_proto_rawDescGZIP(), []int{9}
}

func (x *IngestResponse) GetAccepted() uint32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	SinceUnixNano int64                  `protobuf:"varint,3,opt,name=since_unix_nano,json=sinceUnixNano,proto3" json:"since_unix_nano,omitempty"`
	Limit         uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_protobuf_agentknox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agentknox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_agentknox_proto_rawDescGZIP(), []int{10}
}

func (x *QueryRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *QueryRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *QueryRequest) GetSinceUnixNano() int64 {
	if x != nil {
		return x.SinceUnixNano
	}
	return 0
}

func (x *QueryRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	TimeUnixNano  int64                  `protobuf:"varint,3,opt,name=time_unix_nano,json=timeUnixNano,proto3" json:"time_unix_nano,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_protobuf_agentknox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agentknox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_protobuf_agentknox_proto_rawDescGZIP(), []int{11}
}

func (x *Record) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Record) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Record) GetTimeUnixNano() int64 {
	if x != nil {
		return x.TimeUnixNano
	}
	return 0
}

func (x *Record) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_protobuf_agentknox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agentknox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_agentknox_proto_rawDescGZIP(), []int{12}
}

func (x *QueryResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type SourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourcesRequest) Reset() {
	*x = SourcesRequest{}
	mi := &file_protobuf_agentknox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourcesRequest) ProtoMessage() {}

func (x *SourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agentknox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourcesRequest.ProtoReflect.Descriptor instead.
func (*SourcesRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_agentknox_proto_rawDescGZIP(), []int{13}
}

type SourceStat struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Source           string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Count            int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	LastSeenUnixNano int64                  `protobuf:"varint,3,opt,name=last_seen_unix_nano,json=lastSeenUnixNano,proto3" json:"last_seen_unix_nano,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SourceStat) Reset() {
	*x = SourceStat{}
	mi := &file_protobuf_agentknox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceStat) ProtoMessage() {}

func (x *SourceStat) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agentknox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceStat.ProtoReflect.Descriptor instead.
func (*SourceStat) Descriptor() ([]byte, []int) {
	return file_protobuf_agentknox_proto_rawDescGZIP(), []int{14}
}

func (x *SourceStat) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SourceStat) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SourceStat) GetLastSeenUnixNano() int64 {
	if x != nil {
		return x.LastSeenUnixNano
	}
	return 0
}

type SourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*SourceStat          `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourcesResponse) Reset() {
	*x = SourcesResponse{}
	mi := &file_protobuf_agentknox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourcesResponse) ProtoMessage() {}

func (x *SourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agentknox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourcesResponse.ProtoReflect.Descriptor instead.
func (*SourcesResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_agentknox_proto_rawDescGZIP(), []int{15}
}

func (x *SourcesResponse) GetSources() []*SourceStat {
	if x != nil {
		return x.Sources
	}
	return nil
}

var File_protobuf_agentknox_proto protoreflect.FileDescriptor

const file_protobuf_agentknox_proto_rawDesc = "" +
	"\n" +
	"\x18protobuf/agentknox.proto\x12\fagentknox.v1\"X\n" +
	"\bEnvelope\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12$\n" +
	"\x0etime_unix_nano\x18\x02 \x01(\x03R\ftimeUnixNano\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"%\n" +
	"\rStreamRequest\x12\x14\n" +
	"\x05kinds\x18\x01 \x03(\tR\x05kinds\"9\n" +
	"\rRecentRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"@\n" +
	"\x0eRecentResponse\x12.\n" +
	"\x06events\x18\x01 \x03(\v2\x16.agentknox.v1.EnvelopeR\x06events\"\x11\n" +
	"\x0fSessionsRequest\".\n" +
	"\x10SessionsResponse\x12\x1a\n" +
	"\bsessions\x18\x01 \x03(\fR\bsessions\"\x11\n" +
	"\x0fPoliciesRequest\"0\n" +
	"\x10PoliciesResponse\x12\x1c\n" +
	"\tsummaries\x18\x01 \x01(\fR\tsummaries\"W\n" +
	"\rIngestRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12.\n" +
	"\x06events\x18\x02 \x03(\v2\x16.agentknox.v1.EnvelopeR\x06events\",\n" +
	"\x0eIngestResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\rR\baccepted\"x\n" +
	"\fQueryRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12&\n" +
	"\x0fsince_unix_nano\x18\x03 \x01(\x03R\rsinceUnixNano\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\"n\n" +
	"\x06Record\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12$\n" +
	"\x0etime_unix_nano\x18\x03 \x01(\x03R\ftimeUnixNano\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"?\n" +
	"\rQueryResponse\x12.\n" +
	"\arecords\x18\x01 \x03(\v2\x14.agentknox.v1.RecordR\arecords\"\x10\n" +
	"\x0eSourcesRequest\"i\n" +
	"\n" +
	"SourceStat\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12-\n" +
	"\x13last_seen_unix_nano\x18\x03 \x01(\x03R\x10lastSeenUnixNano\"E\n" +
	"\x0fSourcesResponse\x122\n" +
	"\asources\x18\x01 \x03(\v2\x18.agentknox.v1.SourceStatR\asources2\xb5\x02\n" +
	"\x0fAgentKnoxExport\x12?\n" +
	"\x06Stream\x12\x1b.agentknox.v1.StreamRequest\x1a\x16.agentknox.v1.Envelope0\x01\x12C\n" +
	"\x06Recent\x12\x1b.agentknox.v1.RecentRequest\x1a\x1c.agentknox.v1.RecentResponse\x12M\n" +
	"\fListSessions\x12\x1d.agentknox.v1.SessionsRequest\x1a\x1e.agentknox.v1.SessionsResponse\x12M\n" +
	"\fListPolicies\x12\x1d.agentknox.v1.PoliciesRequest\x1a\x1e.agentknox.v1.PoliciesResponse2\xe4\x01\n" +
	"\x13AgentKnoxAggregator\x12C\n" +
	"\x06Ingest\x12\x1b.agentknox.v1.IngestRequest\x1a\x1c.agentknox.v1.IngestResponse\x12@\n" +
	"\x05Query\x12\x1a.agentknox.v1.QueryRequest\x1a\x1b.agentknox.v1.QueryResponse\x12F\n" +
	"\aSources\x12\x1c.agentknox.v1.SourcesRequest\x1a\x1d.agentknox.v1.SourcesResponseB3Z1github.com/boanlab/agentknox/protobuf/agentknoxpbb\x06proto3"

var (
	file_protobuf_agentknox_proto_rawDescOnce sync.Once
	file_protobuf_agentknox_proto_rawDescData []byte
)

func file_protobuf_agentknox_proto_rawDescGZIP() []byte {
	file_protobuf_agentknox_proto_rawDescOnce.Do(func() {
		file_protobuf_agentknox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_agentknox_proto_rawDesc), len(file_protobuf_agentknox_proto_rawDesc)))
	})
	return file_protobuf_agentknox_proto_rawDescData
}

var file_protobuf_agentknox_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_protobuf_agentknox_proto_goTypes = []any{
	(*Envelope)(nil),         // 0: agentknox.v1.Envelope
	(*StreamRequest)(nil),    // 1: agentknox.v1.StreamRequest
	(*RecentRequest)(nil),    // 2: agentknox.v1.RecentRequest
	(*RecentResponse)(nil),   // 3: agentknox.v1.RecentResponse
	(*SessionsRequest)(nil),  // 4: agentknox.v1.SessionsRequest
	(*SessionsResponse)(nil), // 5: agentknox.v1.SessionsResponse
	(*PoliciesRequest)(nil),  // 6: agentknox.v1.PoliciesRequest
	(*PoliciesResponse)(nil), // 7: agentknox.v1.PoliciesResponse
	(*IngestRequest)(nil),    // 8: agentknox.v1.IngestRequest
	(*IngestResponse)(nil),   // 9: agentknox.v1.IngestResponse
	(*QueryRequest)(nil),     // 10: agentknox.v1.QueryRequest
	(*Record)(nil),           // 11: agentknox.v1.Record
	(*QueryResponse)(nil),    // 12: agentknox.v1.QueryResponse
	(*SourcesRequest)(nil),   // 13: agentknox.v1.SourcesRequest
	(*SourceStat)(nil),       // 14: agentknox.v1.SourceStat
	(*SourcesResponse)(nil),  // 15: agentknox.v1.SourcesResponse
}
var file_protobuf_agentknox_proto_depIdxs = []int32{
	0,  // 0: agentknox.v1.RecentResponse.events:type_name -> agentknox.v1.Envelope
	0,  // 1: agentknox.v1.IngestRequest.events:type_name -> agentknox.v1.Envelope
	11, // 2: agentknox.v1.QueryResponse.records:type_name -> agentknox.v1.Record
	14, // 3: agentknox.v1.SourcesResponse.sources:type_name -> agentknox.v1.SourceStat
	1,  // 4: agentknox.v1.AgentKnoxExport.Stream:input_type -> agentknox.v1.StreamRequest
	2,  // 5: agentknox.v1.AgentKnoxExport.Recent:input_type -> agentknox.v1.RecentRequest
	4,  // 6: agentknox.v1.AgentKnoxExport.ListSessions:input_type -> agentknox.v1.SessionsRequest
	6,  // 7: agentknox.v1.AgentKnoxExport.ListPolicies:input_type -> agentknox.v1.PoliciesRequest
	8,  // 8: agentknox.v1.AgentKnoxAggregator.Ingest:input_type -> agentknox.v1.IngestRequest
	10, // 9: agentknox.v1.AgentKnoxAggregator.Query:input_type -> agentknox.v1.QueryRequest
	13, // 10: agentknox.v1.AgentKnoxAggregator.Sources:input_type -> agentknox.v1.SourcesRequest
	0,  // 11: agentknox.v1.AgentKnoxExport.Stream:output_type -> agentknox.v1.Envelope
	3,  // 12: agentknox.v1.AgentKnoxExport.Recent:output_type -> agentknox.v1.RecentResponse
	5,  // 13: agentknox.v1.AgentKnoxExport.ListSessions:output_type -> agentknox.v1.SessionsResponse
	7,  // 14: agentknox.v1.AgentKnoxExport.ListPolicies:output_type -> agentknox.v1.PoliciesResponse
	9,  // 15: agentknox.v1.AgentKnoxAggregator.Ingest:output_type -> agentknox.v1.IngestResponse
	12, // 16: agentknox.v1.AgentKnoxAggregator.Query:output_type -> agentknox.v1.QueryResponse
	15, // 17: agentknox.v1.AgentKnoxAggregator.Sources:output_type -> agentknox.v1.SourcesResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_protobuf_agentknox_proto_init() }
func file_protobuf_agentknox_proto_init() {
	if File_protobuf_agentknox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_agentknox_proto_rawDesc), len(file_protobuf_agentknox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protobuf_agentknox_proto_goTypes,
		DependencyIndexes: file_protobuf_agentknox_proto_depIdxs,
		MessageInfos:      file_protobuf_agentknox_proto_msgTypes,
	}.Build()
	File_protobuf_agentknox_proto = out.File
	file_protobuf_agentknox_proto_goTypes = nil
	file_protobuf_agentknox_proto_depIdxs = nil
}
