// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 BoanLab @ Dankook University
//
// AgentKnox gRPC transport. The daemon streams and replays events over the
// AgentKnoxExport service; daemons forward to a central collector over the
// AgentKnoxAggregator service. Event payloads travel as JSON-encoded
// pkg/types.* values inside an Envelope, so the wire contract stays faithful to
// the canonical Go types without mirroring every nested field here.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: protobuf/agentknox.proto

package agentknoxpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentKnoxExport_Stream_FullMethodName       = "/agentknox.v1.AgentKnoxExport/Stream"
	AgentKnoxExport_Recent_FullMethodName       = "/agentknox.v1.AgentKnoxExport/Recent"
	AgentKnoxExport_ListSessions_FullMethodName = "/agentknox.v1.AgentKnoxExport/ListSessions"
	AgentKnoxExport_ListPolicies_FullMethodName = "/agentknox.v1.AgentKnoxExport/ListPolicies"
)

// AgentKnoxExportClient is the client API for AgentKnoxExport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentKnoxExportClient interface {
	Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Envelope], error)
	Recent(ctx context.Context, in *RecentRequest, opts ...grpc.CallOption) (*RecentResponse, error)
	ListSessions(ctx context.Context, in *SessionsRequest, opts ...grpc.CallOption) (*SessionsResponse, error)
	ListPolicies(ctx context.Context, in *PoliciesRequest, opts ...grpc.CallOption) (*PoliciesResponse, error)
}

type agentKnoxExportClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentKnoxExportClient(cc grpc.ClientConnInterface) AgentKnoxExportClient {
	return &agentKnoxExportClient{cc}
}

func (c *agentKnoxExportClient) Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Envelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentKnoxExport_ServiceDesc.Streams[0], AgentKnoxExport_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, Envelope]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentKnoxExport_StreamClient = grpc.ServerStreamingClient[Envelope]

func (c *agentKnoxExportClient) Recent(ctx context.Context, in *RecentRequest, opts ...grpc.CallOption) (*RecentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecentResponse)
	err := c.cc.Invoke(ctx, AgentKnoxExport_Recent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentKnoxExportClient) ListSessions(ctx context.Context, in *SessionsRequest, opts ...grpc.CallOption) (*SessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionsResponse)
	err := c.cc.Invoke(ctx, AgentKnoxExport_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentKnoxExportClient) ListPolicies(ctx context.Context, in *PoliciesRequest, opts ...grpc.CallOption) (*PoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PoliciesResponse)
	err := c.cc.Invoke(ctx, AgentKnoxExport_ListPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentKnoxExportServer is the server API for AgentKnoxExport service.
// All implementations must embed UnimplementedAgentKnoxExportServer
// for forward compatibility.
type AgentKnoxExportServer interface {
	Stream(*StreamRequest, grpc.ServerStreamingServer[Envelope]) error
	Recent(context.Context, *RecentRequest) (*RecentResponse, error)
	ListSessions(context.Context, *SessionsRequest) (*SessionsResponse, error)
	ListPolicies(context.Context, *PoliciesRequest) (*PoliciesResponse, error)
	mustEmbedUnimplementedAgentKnoxExportServer()
}

// UnimplementedAgentKnoxExportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentKnoxExportServer struct{}

func (UnimplementedAgentKnoxExportServer) Stream(*StreamRequest, grpc.ServerStreamingServer[Envelope]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedAgentKnoxExportServer) Recent(context.Context, *RecentRequest) (*RecentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Recent not implemented")
}
func (UnimplementedAgentKnoxExportServer) ListSessions(context.Context, *SessionsRequest) (*SessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedAgentKnoxExportServer) ListPolicies(context.Context, *PoliciesRequest) (*PoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPolicies not implemented")
}
func (UnimplementedAgentKnoxExportServer) mustEmbedUnimplementedAgentKnoxExportServer() {}
func (UnimplementedAgentKnoxExportServer) testEmbeddedByValue()                         {}

// UnsafeAgentKnoxExportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentKnoxExportServer will
// result in compilation errors.
type UnsafeAgentKnoxExportServer interface {
	mustEmbedUnimplementedAgentKnoxExportServer()
}

func RegisterAgentKnoxExportServer(s grpc.ServiceRegistrar, srv AgentKnoxExportServer) {
	// If the following call panics, it indicates UnimplementedAgentKnoxExportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentKnoxExport_ServiceDesc, srv)
}

func _AgentKnoxExport_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentKnoxExportServer).Stream(m, &grpc.GenericServerStream[StreamRequest, Envelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentKnoxExport_StreamServer = grpc.ServerStreamingServer[Envelope]

func _AgentKnoxExport_Recent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentKnoxExportServer).Recent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentKnoxExport_Recent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentKnoxExportServer).Recent(ctx, req.(*RecentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentKnoxExport_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentKnoxExportServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentKnoxExport_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentKnoxExportServer).ListSessions(ctx, req.(*SessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentKnoxExport_ListPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentKnoxExportServer).ListPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentKnoxExport_ListPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentKnoxExportServer).ListPolicies(ctx, req.(*PoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentKnoxExport_ServiceDesc is the grpc.ServiceDesc for AgentKnoxExport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentKnoxExport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentknox.v1.AgentKnoxExport",
	HandlerType: (*AgentKnoxExportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recent",
			Handler:    _AgentKnoxExport_Recent_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _AgentKnoxExport_ListSessions_Handler,
		},
		{
			MethodName: "ListPolicies",
			Handler:    _AgentKnoxExport_ListPolicies_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _AgentKnoxExport_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobuf/agentknox.proto",
}

const (
	AgentKnoxAggregator_Ingest_FullMethodName  = "/agentknox.v1.AgentKnoxAggregator/Ingest"
	AgentKnoxAggregator_Query_FullMethodName   = "/agentknox.v1.AgentKnoxAggregator/Query"
	AgentKnoxAggregator_Sources_FullMethodName = "/agentknox.v1.AgentKnoxAggregator/Sources"
)

// AgentKnoxAggregatorClient is the client API for AgentKnoxAggregator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentKnoxAggregatorClient interface {
	Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	Sources(ctx context.Context, in *SourcesRequest, opts ...grpc.CallOption) (*SourcesResponse, error)
}

type agentKnoxAggregatorClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentKnoxAggregatorClient(cc grpc.ClientConnInterface) AgentKnoxAggregatorClient {
	return &agentKnoxAggregatorClient{cc}
}

func (c *agentKnoxAggregatorClient) Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, AgentKnoxAggregator_Ingest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentKnoxAggregatorClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, AgentKnoxAggregator_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentKnoxAggregatorClient) Sources(ctx context.Context, in *SourcesRequest, opts ...grpc.CallOption) (*SourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SourcesResponse)
	err := c.cc.Invoke(ctx, AgentKnoxAggregator_Sources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentKnoxAggregatorServer is the server API for AgentKnoxAggregator service.
// All implementations must embed UnimplementedAgentKnoxAggregatorServer
// for forward compatibility.
type AgentKnoxAggregatorServer interface {
	Ingest(context.Context, *IngestRequest) (*IngestResponse, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	Sources(context.Context, *SourcesRequest) (*SourcesResponse, error)
	mustEmbedUnimplementedAgentKnoxAggregatorServer()
}

// UnimplementedAgentKnoxAggregatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentKnoxAggregatorServer struct{}

func (UnimplementedAgentKnoxAggregatorServer) Ingest(context.Context, *IngestRequest) (*IngestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedAgentKnoxAggregatorServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedAgentKnoxAggregatorServer) Sources(context.Context, *SourcesRequest) (*SourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sources not implemented")
}
func (UnimplementedAgentKnoxAggregatorServer) mustEmbedUnimplementedAgentKnoxAggregatorServer() {}
func (UnimplementedAgentKnoxAggregatorServer) testEmbeddedByValue()                             {}

// UnsafeAgentKnoxAggregatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentKnoxAggregatorServer will
// result in compilation errors.
type UnsafeAgentKnoxAggregatorServer interface {
	mustEmbedUnimplementedAgentKnoxAggregatorServer()
}

func RegisterAgentKnoxAggregatorServer(s grpc.ServiceRegistrar, srv AgentKnoxAggregatorServer) {
	// If the following call panics, it indicates UnimplementedAgentKnoxAggregatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentKnoxAggregator_ServiceDesc, srv)
}

func _AgentKnoxAggregator_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentKnoxAggregatorServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentKnoxAggregator_Ingest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentKnoxAggregatorServer).Ingest(ctx, req.(*IngestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentKnoxAggregator_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentKnoxAggregatorServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentKnoxAggregator_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentKnoxAggregatorServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentKnoxAggregator_Sources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentKnoxAggregatorServer).Sources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentKnoxAggregator_Sources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentKnoxAggregatorServer).Sources(ctx, req.(*SourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentKnoxAggregator_ServiceDesc is the grpc.ServiceDesc for AgentKnoxAggregator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentKnoxAggregator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentknox.v1.AgentKnoxAggregator",
	HandlerType: (*AgentKnoxAggregatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _AgentKnoxAggregator_Ingest_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _AgentKnoxAggregator_Query_Handler,
		},
		{
			MethodName: "Sources",
			Handler:    _AgentKnoxAggregator_Sources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/agentknox.proto",
}
