#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
set -e

if [ "$1" = "remove" ] && [ -d /run/systemd/system ]; then
    systemctl stop agentknox.service >/dev/null 2>&1 || true
    systemctl disable agentknox.service >/dev/null 2>&1 || true
fi

exit 0
